name: Test and Lint

on: 
 push:
   branches:
     - "main"

jobs:
 setup:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      # goのセットアップ
      - name: Set up golang
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.4'
